AWSTemplateFormatVersion: 2010-09-09
Description: Deploy all services related to VMC Workshop
Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String 
    Default: student#

  StudentPassword:
    Description: Password for student account
    Type: String 
    Default: VMware1!
  
  Profile:
    Description: determines locations for url and buckets
    Type: String 
    Default: vmcexpert1
  
  yamlURL:
    Description: URL location to yaml
    Type: String 
    Default: https://vmcexpert2-us-east-1-cf.s3.amazonaws.com/

  vpcCIDR1:
    Description: Please enter the IP range (CIDR notation) for this VPC
    Type: String 
    Default: 172.1.0.0/16

  Subnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the first Availability Zone
    Type: String 
    Default: 172.1.0.0/20

  Subnet2CIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the second Availability Zone
    Type: String 
    Default: 172.1.16.0/20

  vpcCIDR2:
    Description: Please enter the IP range (CIDR notation) for this VPC
    Type: String 
    Default: 10.1.0.0/20

  Subnet3CIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the first Availability Zone
    Type: String 
    Default: 10.1.1.0/24

  Subnet4CIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the second Availability Zone
    Type: String 
    Default: 10.1.2.0/24
  
  VCDR:
    Description: VCDR instance or not
    Type: String
    AllowedValues:
      - 'True'
      - 'False'

Conditions:
  isVCDR: !Equals
    - !Ref VCDR
    - 'False'

Resources:
  InfraStack: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: !Sub "${yamlURL}workshop-infra.yml"
      Parameters: 
        EnvironmentName: !Ref EnvironmentName
        StudentPassword: !Ref StudentPassword
        vpcCIDR1: !Ref vpcCIDR1
        Subnet1CIDR: !Ref Subnet1CIDR
        Subnet2CIDR: !Ref Subnet2CIDR
        vpcCIDR2: !Ref vpcCIDR2
        Subnet3CIDR: !Ref Subnet3CIDR
        Subnet4CIDR: !Ref Subnet4CIDR
        VCDR: !Ref VCDR

  ServiceStack: 
    Type: AWS::CloudFormation::Stack
    Condition: isVCDR
    DependsOn: InfraStack
    Properties:
      TemplateURL: !Sub "${yamlURL}workshop-services.yml"
      Parameters: 
        NetworkStackName: !Ref EnvironmentName
        Profile: !Ref Profile

        # VPCID1: !GetAtt InfraStack.Outputs.VPC1
        # StudentPassword: !Ref StudentPassword
        # SubnetID1: !GetAtt InfraStack.Outputs.AZSubnetId1
        # SubnetID2: !GetAtt InfraStack.Outputs.AZSubnetId2
